default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: flashcards_development
  host: localhost
  pool: 5
  username: flashcards
  password: ys321artem

test:
  <<: *default
  database: flashcards_test
  host: localhost
  pool: 5
  username: flashcards
  password: ys321artem
  
production:
  <<: *default
  database: flashcards_production
  username: flashcards
  password: <%= ENV['FLASHCARDS_DATABASE_PASSWORD'] %>
