# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e44201b59482cace3e01e21c564761f1e56edea1e44d28c82be3a140395d31eeb7ed60b399d95795d6c960b4265378956876861572fd4651555c7b7117ff03c

test:
  secret_key_base: 43cded0d51239bc398b7a68c4611e19b19c1d51f82545fb5e7afd0a9c1a105c59b1f8b90fc4cac959b38b1e359620e69c45344c2d88980a34371dad7f80ca619

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
